### ISSUE TITLE
How I can use this code without google functions, I use Heroku?

### ISSUE THREAD

**Issue by zentechthaingo** [actions-on-google/dialogflow-number-genie-nodejs#2]
I want to run this example without use google functions. I am beginning with nodejs, can you help me?

**Comment by LeonNicholls** [comment]
Here you can see the recent changes we made to migrate to Cloud Functions: https://github.com/actions-on-google/apiai-number-genie-nodejs/commit/9095abf93ec830d66be3190d23f3a3c9768ef62d

**Comment by zentechthaingo** [comment]
thanks for you help, I got that ! :)
