### ISSUE TITLE
input.welcome intent not handled

### ISSUE THREAD

**Issue by thisisananth** [actions-on-google/dialogflow-number-genie-nodejs#8]
I imported the project into an app on firebase, deployed it and tried to test it. The default intent I get is input.welcome and I don't see any handler for that in the code. I'm thinking that should be there as that is the intent which starts the game. Am I missing something ?
 Handled intents are 
const Actions = {
  GENERATE_ANSWER: 'generate_answer',
  CHECK_GUESS: 'check_guess',
  QUIT: 'quit',
  PLAY_AGAIN_YES: 'play_again_yes',
  PLAY_AGAIN_NO: 'play_again_no',
  DEFAULT_FALLBACK: 'input.unknown',
  UNKNOWN_DEEPLINK: 'deeplink.unknown',
  NUMBER_DEEPLINK: 'deeplink.number',
  DONE_YES: 'done_yes',
  DONE_NO: 'done_no',
  REPEAT: 'repeat'
};

**Comment by Canain** [comment]
Hi, it looks like you didn't import the Dialogflow project zip into your Dialogflow agent.

You should follow steps 4-6 in the README to import it:
### Steps
4. Click on the gear icon to see the project settings.
5. Select *Export and Import*.
6. Select *Restore from zip*. Follow the directions to restore from the `NumberGenie.zip` file in this repo.

This project's Dialogflow agent does not use the default welcome intent. It has its own called `start_game` which triggers the `generate_answer` action which is handled in the code [here](https://github.com/actions-on-google/dialogflow-number-genie-nodejs/blob/master/functions/index.js#L118).

How the welcome intent is determined for Actions on Google using Dialogflow is by the `GOOGLE_ASSISTANT_WELCOME` intent which in this project's agent is put on the `start_game` intent.

**Comment by thisisananth** [comment]
Thanks Canain. That makes sense.
