### ISSUE TITLE
Error deploying on Firebase

### ISSUE THREAD

**Issue by davidmarinangeli** [actions-on-google/dialogflow-number-genie-nodejs#9]
When I try to send the command `firebase deploy` the CLI give me ann error

`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! guess-a-number@0.0.1 lint: `eslint --fix "**/*.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the guess-a-number@0.0.1 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\david\AppData\Roaming\npm-cache\_logs\2018-04-03T13_43_08_308Z-debug.log`

What is this?

**Comment by asjgi** [comment]
I have a problem like that too.

**Comment by asjgi** [comment]
@davidmarinangeli hello 
I solve like that follow link
https://stackoverflow.com/questions/50501988/cannot-find-module-dialogflow-fulfillment?rq=1

**Comment by LeonNicholls** [comment]
Closing since the solutions from @asjgi should work.
